### PR TITLE
Implement WARP+ Unlimited subscription redeem

### PR DESCRIPTION
**Pull request by perillamint**
Implement WARP+ Unlimited subscription redeem using account API.

Thanks to @teslamint for a tip.

### CODE REVIEW

**Comment by perillamint** [comment]
This will fix issue #6

**Comment by cpbotha** [comment]
I just tried this out with my existing Warp+ Unlimited license key, it works like a charm.

**Comment by perillamint** [comment]
Fixed to replace WARP+ key only when the given key is different from registered one.

**Comment by ViRb3** [comment]
I will take a look at this first thing tomorrow after I submit my assignment. Thanks for the patience!

**Comment by LuuOW** [comment]
Sr can you tell me how to or were find the API calls to get the licence key ?

**Comment by teslamint** [comment]
> Sr can you tell me how to or were find the API calls to get the licence key ?

You can get the license key from account tab in the app. (tap the hamburger menu)

**Comment by LuuOW** [comment]
> > Sr can you tell me how to or were find the API calls to get the licence key ?
> 
> You can get the license key from account tab in the app. (tap the hamburger menu)

I'm referring to the licence key generated by the script, not the default licence key in the 1.1.1.1 app

**Comment by teslamint** [comment]
> > > Sr can you tell me how to or were find the API calls to get the licence key ?
> > 
> > 
> > You can get the license key from account tab in the app. (tap the hamburger menu)
> 
> I'm referring to the licence key generated by the script, not the default licence key in the 1.1.1.1 app

If you are looking for the license key with new account generated by script, send the GET request to `{api}/reg/{account_id}/account` with access_token as a Bearer token.

**Comment by LuuOW** [comment]
> > > > Sr can you tell me how to or were find the API calls to get the licence key ?
> > > 
> > > 
> > > You can get the license key from account tab in the app. (tap the hamburger menu)
> > 
> > I'm referring to the licence key generated by the script, not the default licence key in the 1.1.1.1 app
> 
> If you are looking for the license key with new account generated by script, send the GET request to `{api}/reg/{account_id}/account` with access_token as a Bearer token.

Using the access token as bearer token and doing the request like this
 https://api.cloudflare.com/client/v0a848/reg/X0XXa1f7-XXXXXX-a2d2-XX879cad6de/account

I get error 505 not allowed

**Comment by teslamint** [comment]
> > > > > Sr can you tell me how to or were find the API calls to get the licence key ?
> > > > 
> > > > 
> > > > You can get the license key from account tab in the app. (tap the hamburger menu)
> > > 
> > > 
> > > I'm referring to the licence key generated by the script, not the default licence key in the 1.1.1.1 app
> > 
> > 
> > If you are looking for the license key with new account generated by script, send the GET request to `{api}/reg/{account_id}/account` with access_token as a Bearer token.
> 
> Using the access token as bearer token and doing the request like this
> https://api.cloudflare.com/client/v0a848/reg/X0XXa1f7-XXXXXX-a2d2-XX879cad6de/account
> 
> I get error 505 not allowed

try: `https://api.cloudflareclient.com/v0a848/reg/X0XXa1f7-XXXXXX-a2d2-XX879cad6de/account`

**Comment by perillamint** [comment]
It seems Argo routing does not active unless the device is marked as active, so I added code to mark a device as an active device.

Any idea for a user interface? @ViRb3  (I don't think current user interface (asking y/n on startup) is not so good for automated users)

**Comment by ViRb3** [comment]
I assume you mean a graphical user interface (GUI)? If that's the case, unfortunately I have no plans for that. This tool is mean to be a simple, portable CLI tool. Regarding automation, that is a good point, I am tracking it in #8. Now, I am working on reviewing Cloudflare's changes and merging this PR.

**Comment by LuuOW** [comment]
> > > > > > Sr can you tell me how to or were find the API calls to get the licence key ?
> > > > > 
> > > > > 
> > > > > You can get the license key from account tab in the app. (tap the hamburger menu)
> > > > 
> > > > 
> > > > I'm referring to the licence key generated by the script, not the default licence key in the 1.1.1.1 app
> > > 
> > > 
> > > If you are looking for the license key with new account generated by script, send the GET request to `{api}/reg/{account_id}/account` with access_token as a Bearer token.
> > 
> > Using the access token as bearer token and doing the request like this
> > https://api.cloudflare.com/client/v0a848/reg/X0XXa1f7-XXXXXX-a2d2-XX879cad6de/account
> > 
> > I get error 505 not allowed
> 
> try: `https://api.cloudflareclient.com/v0a848/reg/X0XXa1f7-XXXXXX-a2d2-XX879cad6de/account`
> 

Done! Thank you so much for your help i finally could get the key, thank you <3

**Comment by ViRb3** [comment]
@perillamint Thank you very much for your contribution! I refactored the code a bit and added some logic to handle edge cases, but apart from that your work is perfect!

**Pull request merged**
